# File: azure-pipelines.yml
trigger:
- main

extends:
  template: testing-template.yml
  parameters:
    buildSteps:  
      - bash: echo Test1 #Passes
        displayName: succeed1
      - bash: echo "Test2"
        displayName: succeed2
      # Step is rejected by raising a YAML syntax error: Unexpected value 'CmdLine@2'
      # Step is rejected by raising a YAML syntax error: Unexpected value 'CmdLine@2'
      - script: echo "Script Test4"
